//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wx.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrizeSettings
    {
        public string PrizeNo { get; set; }
        public string PrizeName { get; set; }
        public string SalesArea { get; set; }
        public Nullable<int> PrizeType { get; set; }
        public Nullable<int> Money { get; set; }
        public string Description { get; set; }
        public Nullable<int> PrizeCount { get; set; }
        public Nullable<int> WinningCount { get; set; }
        public Nullable<bool> ClosePrize { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
    }
}
