//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wx.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrizeCode
    {
        public string BarCode { get; set; }
        public string PrizeNo { get; set; }
        public string PrizeName { get; set; }
        public Nullable<System.DateTime> PrizeDate { get; set; }
        public Nullable<bool> AwardFlag { get; set; }
        public Nullable<System.DateTime> AwardDate { get; set; }
        public string openId { get; set; }
        public Nullable<System.DateTime> FirstQuery { get; set; }
        public Nullable<int> QueryCount { get; set; }
    }
}
